# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :check do
    gradle(task: "check")
  end

  desc "Create GitHub PR to `payjp/payjp-android` from internal repo. (internal only)"
  lane :create_pr_to_public do
    public_repo = 'payjp/payjp-android'
    last_commit_hash = last_git_commit[:abbreviated_commit_hash]
    new_branch = "internal/#{last_commit_hash}"

    sh("git checkout -b #{new_branch}")
    sh("git remote add public git@github.com:payjp/payjp-android.git")
    push_to_git_remote(
      remote: 'public',
      remote_branch: new_branch
    )

    pr_url = create_pull_request(
      repo: public_repo,
      base: 'master',
      title: "internal update:#{last_commit_hash}",
      api_token: ENV['GITHUB_API_TOKEN']
    )

    slack(
      message: ":rocket: PR is created! Please fill in the blank PR description:information_desk_person:\n#{pr_url}",
      success: true
    )
  end
end
